### ISSUE TITLE
Dataset Issues

### ISSUE THREAD

**Issue by Penge666** [TruongKhang/TopicFM#9]
Could the author privately distribute the dataset? I can't download here。QAQ

**Comment by TruongKhang** [comment]
Hello @Penge666, which dataset do you want? 
The training dataset is a large dataset. I don't have enough space to share them.

**Comment by Penge666** [comment]
okay, thank youQWQ

**Comment by Penge666** [comment]
I want to ScanNet.I don't know if it's okay？

**Comment by TruongKhang** [comment]
For ScanNet, the test data is available as described in my `README` file. The training data is really large (up to TeraByte) and if you want to download this dataset, you have to contact the authors of this dataset and sign an agreement that only allows you to use this dataset for research purposes. 
In my paper, I didn't train on ScanNet because it takes a very long time to finish. I don't have many GPUs

**Comment by Penge666** [comment]
Oh, well, okay, I understand，thank you🙂
